.\" Manpage for hangman
.TH hangman 6 "08 Apr 2018"
.SH NAME
hangman \- a bash version of the classic hangman
.SH SYNOPSIS
.B hangman 
[
.B options
] [
.B argument
]
.SH DESCRIPTION
hangman is a game where you guess the right word. The game allows you to specify a word or a dictionary from which the game will chose a random word.
.PP
.TP
.B \-w
Put in a word while the other person is not watching
.TP
.B \-d
Specify your own dictionary
.SH AUTHOR
Peter-Jan Gootzen (pjmgootz@avans.nl) and Bram-Boris Meerlo (bbmeerlo@avans.nl)
